"""Generates the built-in food table from data/foods_ko.tsv (curated) plus
data/foods_mfds.tsv (imported from the 식약처 DB by tool/import_mfds.py, if
present):

  lib/data/food_db.g.dart   (const Dart list for the app)
  preview/src/foods.json    (embedded into the single-file preview)

Also sanity-checks each row (kcal vs 4/4/9 macro energy).
Run: python3 tool/gen_foods.py
"""
import hashlib
import json
import os
import re
import sys

ROOT = os.path.join(os.path.dirname(__file__), "..")
SRC = os.path.join(ROOT, "data", "foods_ko.tsv")
MFDS = os.path.join(ROOT, "data", "foods_mfds.tsv")


def slug(name: str, prefix: str) -> str:
    # Stable across edits: meals store this id. Imported foods ("m") number
    # in the hundreds of thousands on the server, so they get more digits.
    digits = 8 if prefix == "f" else 12
    return prefix + hashlib.sha1(name.encode("utf-8")).hexdigest()[:digits]


def load(path=SRC, prefix="f"):
    foods = []
    if not os.path.exists(path):
        return foods
    for n, line in enumerate(open(path, encoding="utf-8"), 1):
        line = line.rstrip("\n")
        if not line or line.startswith("#"):
            continue
        cols = line.split("\t")
        if len(cols) not in (8, 9):
            sys.exit(f"line {n}: expected 8 or 9 columns, got {len(cols)}")
        name, aliases, cat, kcal, p, c, f, units = cols[:8]
        unknown = cols[8].strip() if len(cols) == 9 else ""  # macros not published: p/c/f
        us = []
        for u in units.split(";"):
            label, grams = u.rsplit(":", 1)
            us.append((label.strip(), float(grams)))
        foods.append({
            "id": slug(name.strip(), prefix),
            "name": name.strip(),
            "aliases": [a.strip() for a in aliases.split(",") if a.strip()],
            "cat": cat.strip(),
            "kcal": float(kcal), "p": float(p), "c": float(c), "f": float(f),
            "units": us,
            "unknown": unknown,
        })
    return foods


def check(foods, strict=True):
    names, ids = set(), set()
    for fd in foods:
        if fd["name"] in names:
            sys.exit(f"duplicate name: {fd['name']}")
        if fd["id"] in ids:
            sys.exit(f"duplicate id {fd['id']}: {fd['name']}")
        names.add(fd["name"])
        ids.add(fd["id"])
        macro = fd["p"] * 4 + fd["c"] * 4 + fd["f"] * 9
        if not strict or fd["unknown"] or fd["cat"] == "주류" or fd["kcal"] < 20:
            continue  # alcohol energy / near-zero drinks
        if abs(macro - fd["kcal"]) / fd["kcal"] > 0.25:
            print(f"warn: {fd['name']} kcal {fd['kcal']} vs macros {macro:.0f}")


def num(v: float) -> str:
    return str(int(v)) if v == int(v) else repr(v)


def dart(foods) -> str:
    esc = lambda s: s.replace("\\", "\\\\").replace("'", "\\'").replace("$", "\\$")
    out = [
        "// GENERATED by tool/gen_foods.py from data/foods_ko.tsv. Do not edit.",
        "// Approximate reference values per 100 g.",
        "import 'food.dart';",
        "",
        "const builtInFoods = <Food>[",
    ]
    for fd in foods:
        aliases = ", ".join(f"'{esc(a)}'" for a in fd["aliases"])
        units = ", ".join(f"FoodUnit('{esc(l)}', {num(g)})" for l, g in fd["units"])
        out.append(
            f"  Food('{fd['id']}', '{esc(fd['name'])}', [{aliases}], '{esc(fd['cat'])}', "
            f"{num(fd['kcal'])}, {num(fd['p'])}, {num(fd['c'])}, {num(fd['f'])}, [{units}]"
            + (f", unknown: '{fd['unknown']}'" if fd["unknown"] else "") + "),"
        )
    out.append("];")
    return "\n".join(out) + "\n"


def main():
    foods = load()
    check(foods)
    curated = {f["name"].lower() for f in foods}
    imported = [f for f in load(MFDS, "m") if f["name"].lower() not in curated]
    check(imported, strict=False)
    foods += imported
    with open(os.path.join(ROOT, "lib", "data", "food_db.g.dart"), "w", encoding="utf-8") as fh:
        fh.write(dart(foods))
    compact = [[fd["id"], fd["name"], fd["aliases"], fd["cat"], fd["kcal"], fd["p"], fd["c"], fd["f"],
                [[l, g] for l, g in fd["units"]]] + ([fd["unknown"]] if fd["unknown"] else [])
               for fd in foods]
    with open(os.path.join(ROOT, "preview", "src", "foods.json"), "w", encoding="utf-8") as fh:
        json.dump(compact, fh, ensure_ascii=False, separators=(",", ":"))
    print(f"{len(foods)} foods ({len(imported)} imported), {len({f['cat'] for f in foods})} categories")


if __name__ == "__main__":
    main()
